version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_DATABASE: isupipe
    ports:
      - 33306:3306
    security_opt:
      - seccomp:unconfined
    command: --default-authentication-plugin=mysql_native_password
