---
- name: Copy mysqld.cnf
  copy:
    src: ../../etc/mysql/mysqld.{{ env }}.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    mode: 0644

- name: Change file ownership /var/log/mysql/error.log
  ansible.builtin.file:
    path: /var/log/mysql/error.log
    owner: mysql
    group: adm
    mode: 0644

- name: Change file ownership /var/log/mysql/mysql-slow.log
  ansible.builtin.file:
    path: /var/log/mysql/mysql-slow.log
    owner: mysql
    group: adm
    mode: 0644

- name: Restart mysql
  service:
    name: mysql
    state: restarted
    enabled: yes
