---
- name: Prepare env
  copy:
    src: ../../../env.sh.{{ env }}
    dest: /home/isucon/env.sh
    mode: 0755

- name: Build go
  environment:
    PATH: /home/isucon/local/golang/bin:{{ ansible_env.PATH }}
  make:
    chdir: /home/isucon/webapp/go
    target: build
    params:
      DEST: /home/isucon/webapp/go/isupipe

- name: Restart go
  become: true
  service:
    name: isupipe-go.service
    state: restarted
    enabled: yes
