---
reverse: true
sort: sum
matching_groups:
  - /api/user/\w+/theme
  - /api/user/\w+/icon
  - /api/user/\w+/statistics
  - /api/user/\w+
  - /api/user/me
  - /api/user/\w+/livestream
  - /api/user/\w+/livestream/\w+/livecomment
  - /api/user/\w+/livestream/\w+/reaction
  - /api/user/\w+/livestream/\w+/report
  - /api/user/\w+/livestream/\w+/moderate
  - /api/user/\w+/livestream/\w+/enter
  - /api/user/\w+/livestream/\w+/exit
  - /api/user/\w+/livestream/\w+
  - /api/livestream/\w+/livecomment
  - /api/livestream/\w+/reaction
  - /api/livestream/\w+/report
  - /api/livestream/\w+/moderate
  - /api/livestream/\w+/enter
  - /api/livestream/\w+/exit
  - /api/livestream/\w+
  - /api/livestream/search
  - /api/livestream/reservation
  - /api/livestream
output: count,method,uri,1xx,2xx,3xx,4xx,5xx,sum,avg,min,max
