name: Run ssh-keyscan

inputs:
  private_key:
    required: true

runs:
  using: composite
  steps:
    - name: Create ~/.bssh
      shell: bash
      run: mkdir -p ~/.ssh
    - name: Create ~/.ssh/id_ed25519
      shell: bash
      run: echo "${{ inputs.private_key }}" > ~/.ssh/id_ed25519
    - name: Change permission
      shell: bash
      run: chmod 600 ~/.ssh/id_ed25519
    - name: Run ssh-keyscan
      shell: bash
      run: |
        ssh-keyscan -H 13.113.224.90 >> ~/.ssh/known_hosts
        ssh-keyscan -H 52.193.18.45 >> ~/.ssh/known_hosts
        ssh-keyscan -H 35.73.97.79 >> ~/.ssh/known_hosts
