name: Run ssh-keyscan

inputs:
  private_key:
    required: true

runs:
  using: composite
  steps:
    - name: Create ~/.bssh
      shell: bash
      run: mkdir -p ~/.ssh
    - name: Create ~/.ssh/id_ed25519
      shell: bash
      run: echo "${{ inputs.private_key }}" > ~/.ssh/id_ed25519
    - name: Change permission
      shell: bash
      run: chmod 600 ~/.ssh/id_ed25519
    - name: Run ssh-keyscan
      shell: bash
      run: |
        ssh-keyscan -H 133.242.50.233 >> ~/.ssh/known_hosts
        ssh-keyscan -H 133.242.220.134 >> ~/.ssh/known_hosts
        ssh-keyscan -H 133.125.81.90 >> ~/.ssh/known_hosts
