---
- name: Copy id_ed25519
  copy:
    src: ../../etc/ssh/id_ed25519
    dest: /home/isucon/.ssh/id_ed25519

- name: Copy id_ed25519.pub
  copy:
    src: ../../etc/ssh/id_ed25519.pub
    dest: /home/isucon/.ssh/id_ed25519.pub
